HEADERS = {
    'authority': 'eda.yandex.ru',
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'ru',
    'content-type': 'application/json;charset=UTF-8',
    'origin': 'https://eda.yandex.ru',
    'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "YaBrowser";v="24.1", "Yowser";v="2.5"',
    'sec-ch-ua-arch': '"x86"',
    'sec-ch-ua-bitness': '"64"',
    'sec-ch-ua-full-version-list': '"Not_A Brand";v="8.0.0.0", "Chromium";v="120.0.6099.291", "YaBrowser";v="24.1.4.827", "Yowser";v="2.5"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-ch-ua-platform-version': '"10.0.0"',
    'sec-ch-ua-wow64': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36',
    'x-app-version': '16.43.0',
    'x-client-session': 'lu8r2twl-safpmbmus2k-xtw7vbqcowg-4xqx1ffsypc',
    'x-device-id': 'lu8r2twl-k5ysu6zasr-2loh30h496d-3pqle8p3ype',
    'x-platform': 'desktop_web',
}
